// <autogenerated>
//   This file was generated by T4 code generator CodeGeneratorRunner.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Blah.BlahBlah
{

    public partial class Cat
    {
        public static void DoSomething()
        {
            // Do something here
        }
    }
}
